name: macOS CI

on: [push]

jobs:
  macOS-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release]
        cmake-var: [ENABLE_CONAN=ON, ENABLE_CONAN=OFF]

    runs-on: macos-latest
    env:
      BUILD_TYPE: ${{matrix.build-type}}

    steps:
    - uses: actions/checkout@v3
           
    - name: Install dependencies (ENABLE_CONAN=ON)
      if: matrix.cmake-var == 'ENABLE_CONAN=ON'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update
        brew install conan

    - name: Install dependencies (ENABLE_CONAN=OFF)
      if: matrix.cmake-var == 'ENABLE_CONAN=OFF'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update
        brew install glew sdl2 sdl2_image

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -D${{matrix.cmake-var}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j $(sysctl -n hw.ncpu)

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
