name: WASM CI

on: [push]

jobs:
  wasm-build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Install Emscripten
      run: |
        sudo apt-get install git cmake
        sudo apt-get install python3 pip
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
     
    - name: Configure CMake 
      run: |
        source ./emsdk/emsdk_env.sh
        emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        source ./emsdk/emsdk_env.sh
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
