name: Windows CI

on: [push]

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release]
     
    runs-on: windows-latest
    env:
      BUILD_TYPE: ${{matrix.build-type}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Install Conan
      run: pip install conan
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_CONAN=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
